platform :ios, '9.0'

target 'Manager' do
inhibit_all_warnings!

pod 'AFNetworking', '~> 3.2.1'
pod 'JSONModel', '~> 1.3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.1'
pod 'Masonry', '~> 0.6.3'

pod 'BaiduMapKit' #百度地图SDK
pod 'BMKLocationKit' #百度定位

#极光推送
#友盟统计
end
